MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  # STRIDE_SIZE: [12, 12]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0
  DEVICE_ID: "3"
  # SIE_CAMERA: True
  # SIE_COE : 1.0


# _C.FEWSHOT = CN()
# _C.FEWSHOT.NWAY = ""
# _C.FEWSHOT.KSHOT = ""
# _C.FEWSHOT.EPISODE = ""
FEWSHOT:
  NWAY: 5
  KSHOT: 5
  EPISODE: 100

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  # PADDING: 30
  # PIXEL_MEAN: [0.485, 0.456, 0.406]
  # PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 25
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 100
    WARMUP_EPOCHS: 5
  
  STAGE2:
    IMS_PER_BATCH: 25
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 100
    EVAL_PERIOD: 5
    BIAS_LR_FACTOR: 2
  
    STEPS: [30, 50]
    GAMMA: 0.1

FINETUNE:
  WEIGHT_1: '/data/zhengwei/CLIP_ReID/logs/base64_skeychy/ViT-B-16_stage1_120.pth'
  WEIGHT_2: '/data/zhengwei/CLIP_ReID/logs/base64_skeychy/ViT-B-16_60.pth'
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
#   NAMES: ('market1501')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('dukemtmc')
#   ROOT_DIR: ('/home/zhengwei/Desktop/Zhengwei/Projects/datasets')
# OUTPUT_DIR: '/home/zhengwei/Desktop/Zhengwei/Projects/CLIP_ReID/logs/base_visualization'

#   NAMES: ('occ_duke')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

  NAMES: ('sketchy')
  ROOT_DIR: ('/home/zhengwei/my_data/datasets')
  # ROOT_DIR: ('/home/stuyangz/Desktop/Zhengwei/github/datasets')

# OUTPUT_DIR: '/home/zhengwei/my_data/CLIP_ReID/logs/msmt_4-2080ti'
OUTPUT_DIR: '/home/zhengwei/my_data/CLIP_ReID/logs/novel61_skeychy_True5w5s_100e_seed1'

# CUDA_VISIBLE_DEVICES=3 python train_clipreid.py --config_file configs/person/vit_clipreid.yml
